title:       "Vulkan Lessons"
subtitle:    "Vulkan tutorials and study materials"
author:      "Artem Gurevich"
email:       "gurevichae@gmail.com"
baseurl:     ""
url:         "http://glcoder.github.io"
description: >
  OpenGL and Vulkan GAPI programming tutorials and study materials.

encoding:      utf-8
permalink:     pretty
paginate_path: /page:num
timezone:      Europe/Moscow
markdown:      redcarpet
highlighter:   none

redcarpet:
  extensions: ["no_intra_emphasis", "tables", "autolink", "strikethrough", "with_toc_data"]

defaults:
  values:
    author: "Artem Gurevich"
    layout: "default"
