title:       "glcoder's place"
author:      "Artem Gurevich"
email:       "gurevichae@gmail.com"
baseurl:     ""
url:         "http://glcoder.github.io"
description: ""

encoding:      utf-8
permalink:     pretty
paginate_path: /page:num
timezone:      Europe/Moscow
markdown:      kramdown
highlighter:   rouge

kramdown:
  input:     GFM
  hard_wrap: false

defaults:
  values:
    author: "Artem Gurevich"
    layout: "default"
